[tox]
isolated_build = true
envlist = py312-django51
requires =
    tox-poetry-dev-dependencies

[testenv]
poetry_add_dev_dependencies = True
deps =
    django51: Django>=5.1,<5.2
    django-environ
    psycopg2
whitelist_externals =
    poetry
    bash
skip_install = true
commands =
    python -V
    python manage.py version
    pytest .

