name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    # IF copied from https://github.com/psf/black/blob/main/.github/workflows/lint.yml:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Workaround for backports.zoneinfo
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-2020 flake8-bugbear
                         flake8-comprehensions isort mypy pytest pyupgrade safety
      - run: bandit --recursive .
      - run: flake8 --ignore=F401 --max-complexity=15 --max-line-length=138 --show-source --statistics .
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive . || true
      - run: ./manage.py test || true
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py37-plus **/*.py || true
      - run: safety check
