# Generated by Django 5.1.15 on 2026-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ark", "0010_arkevent"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="arkevent",
            name="ark_ark_crea_047fb2_idx",
        ),
        migrations.AddIndex(
            model_name="arkevent",
            index=models.Index(
                fields=["ark", "-created_at"],
                name="ark_arkeven_ark_id_8ae507_idx",
            ),
        ),
    ]
