# Generated by Django 5.1.15 on 2026-04-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ark", "0010_arkevent"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="arkevent",
            new_name="ark_arkeven_ark_id_8ae507_idx",
            old_name="ark_ark_crea_047fb2_idx",
        ),
    ]
