# Generated by Django 4.0.5 on 2026-04-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ark", "0011_rename_ark_ark_crea_047fb2_idx_ark_arkeven_ark_id_8ae507_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="ark",
            name="cdn_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ark",
            name="event_name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="ark",
            name="related_arks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
