# Generated by Django 4.0.5 on 2026-04-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ark", "0012_ark_cdn_url_ark_event_name_ark_related_arks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ark",
            name="related_arks",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
